### PR TITLE
Fix for all day events (#55)

### LINKED ISSUE #55: All Day Events
Thanks so much for this package - you've saved me hours!

Just wanted to report on my findings while trying to work out how to output an 'all day event'.  99% this is down to me not knowing how to use iCal spec/this package, but just wanted to make some notes/ask a question.

From inspecting other feeds that were showing all day events correctly, it looked like the structure needed to be:

`DTSTART;VALUE=DATE:20201101`

To get that output I had to bypass the helper functions, format the date manually with a copy of your 'icalDateFormatLocal' (otherwise the Z at the end caused the event not to display) and manually specify the DATE value.

`event.SetProperty(ics.ComponentPropertyDtStart, t.Start.UTC().Format(icalDateFormatLocal), ics.WithValue("DATE"))`

I imagine that I'm missing a much easier way to do this, but couldn't find it to save my life.

### PR DESCRIPTION
**Pull request by cuvar**
Hopefully, this implementation should fix #55. At least, this solutions seems to have worked for me. I took @kevinmorio's approach mentioned in the issue [here](https://github.com/arran4/golang-ical/issues/55#issuecomment-1358271528).

### CODE REVIEW

**Comment by arran4** [comment]
@cuvar Thanks. I will get back to you in a couple days. I will have to check the RFC(s) for what it says it should be too.

However; 
```
	icalDateFormatLocal      = "20060102"
	icalDateFormat      		 = "20060102"
```

They are the same value.

**Comment by cuvar** [comment]
cool, thanks! I'll add another commit regarding the `icalDateFormatLocal` and `icalDateFormat`

**Comment by arran4** [comment]
Thanks. @cuvar What I'm thinking is that this changes behaviour, so how about we just duplicate the functions and append `Local` (Edit; actually it should really be `UTC` as it's not in the local timezone, we would have to replace the `UTC()` and ask for the timezone they want to use; and if we do that it should be appended with `InLocation` instead of `Local` or `UTC`) to them so we don't impact existing users. We also haven't considered deserialization here but I believe the function is more flexible. 

Another approach would be to make it do a better job at detecting the format of the date/time being used.

**Comment by cuvar** [comment]
I'm sorry, but unfortunately I won't have the time to dive into the code in the next time. Therefore, I just created this shallow fix. If there's more time, I'll have a look into it again.

**Comment by arran4** [comment]
@cuvar Thanks though. Perhaps someone else will come and pick up this PR. Did you get your problem solved at all?

**Comment by cuvar** [comment]
Thanks! Yes, it seemed to solve my issue. My timezone is UTC+1

**Comment by arran4** [comment]
I will still look into this when I get some time to work on this project.

**Pull request closed without merging**
