### PR TITLE
Updated readme

### PR DESCRIPTION
**Pull request by vladbaikov**
Updated the example in the README.
Can you please tell me so good? Or add a description?

### CODE REVIEW

**Comment by arran4** [comment]
Not quite what I meant. Thanks though. I will get back to you on this

**Comment by vladbaikov** [comment]
> Not quite what I meant. Thanks though. I will get back to you on this

I apologize.  Please clarify what needs to be added.  I'm ready.

**Comment by vladbaikov** [comment]
I apologize.  Please clarify what needs to be added.  I'm ready.

**Comment by arran4** [comment]
It's good. Although I will keep this open and use the update elsewhere.

However I was asking for the URL or documentation which covers this extension. Or a reference implementation?

**Pull request closed without merging**
