### PR TITLE
Pull 66 add todo journal

### PR DESCRIPTION
**Pull request by arran4**

### CODE REVIEW

**Comment by arran4** [comment]
Hi @spslater  Sorry about the mistake on https://github.com/arran4/golang-ical/pull/66 when merging in current updates. I have attempted to fix it here. Can you please review to see if I introduced any issues?

**Comment by arran4** [comment]
image

Well that doesn't sound good.

**Comment by arran4** [comment]
Lint saved the day.. Gaps in testing by the looks of it.

**Comment by spslater** [comment]
I'm reading thru it now to make sure everything looks good and catch any new functions that wouldn't have been originally changed.

**Comment by arran4** [comment]
@spslater Thanks. There were a couple of relocations which made the merge a bit harder. If I had more time to work on this there is a lot I would like to improve.

**Comment by spslater** [comment]
For sure, I should've really split it into 3 pull requests to make reviewing it a lot easier. I'll go in and do the official review.  Later I will open a new pull request for any newer functions / ones that I missed. It'll be easier to catch them and make those changes that way. But everything I originally changed looks good.

**Review by spslater — APPROVED** [review]
The merge looks good. Like I just said (I forgot there was a comment box here), I'll make a new pull request for any cosmetic things that don't line up. The newer added `{Get,Set}LastModifiedAt` functions will still work with events, but won't with anything else.

**Pull request merged**
