### PR TITLE
Prefix mailto: for email in organizer property

### PR DESCRIPTION
**Pull request by meain**
Organizer property should be similar to how attendee is handled.

https://github.com/arran4/golang-ical/blob/0fcebed54126830e648865ec05e459ad213986df/components.go#L260-L262

### CODE REVIEW

**Review by arran4 — APPROVED** [review]
LGTM

**Comment by arran4** [comment]
Agreed. Consistency is king, also the spec is very clear on this too: https://www.kanzaki.com/docs/ical/calAddress.html I'm not sure if it can be something else.

This might break some existing deployments. I will get back to this, in a couple days.

**Comment by arran4** [comment]
Need to delay, interview prep.

**Comment by meain** [comment]
I don't if this is "clean", but if you have concerns about the user sending in email with "mailto:" prefix, I think we can probably consider only conditionally adding it by checking the prefix.

**Comment by arran4** [comment]
It makes sense and if there is an issue someone can submit an issue and we can add a new code path. There is almost no need for duplication. `:` is not part of dot-atom https://datatracker.ietf.org/doc/html/rfc2822#section-3.2.4 so I think we are home free with that one.

**Comment by arran4** [comment]
But other than that looks good.

**Comment by arran4** [comment]
haha yep. I'm in a loop. Okay. Nothing more is necessary.

**Review by arran4 — APPROVED** [review]
LGTM

**Pull request merged**
