### PR TITLE
Implement attachment logic

### PR DESCRIPTION
**Pull request by yaknikush**
It will be very useful, if this package has attachment logic implemented. It's kind of simple and well described here:
https://icalendar.org/iCalendar-RFC-5545/3-8-1-1-attachment.html

So I added handy wrappers to create reference and item attachments.

### CODE REVIEW

**Comment by arran4** [comment]
Sorry I didn't notice this. Will also review Friday!

**Comment by arran4** [comment]
LGTM. Sorry no idea why I didn't see this!

**Comment by arran4** [comment]
I have tried to keep the library reversible, so all outputs are valid inputs. Does this handle that?

**Comment by yaknikush** [comment]
I have just written the wrappers for (*VEvent).AddProperty(), have added nothing that couldn't be done using your initial API. So if you are sure that the library is reversible now, then the answer is 'yes'.

**Comment by arran4** [comment]
Awesome.

**Pull request merged**
