### PR TITLE
Add other Components creation and properties methods (#65)

### PR DESCRIPTION
**Pull request by spslater**
Changes for issue #65:
- Add methods to create, add, and get Todo, Journal, Timezone, and Free/Busy components to a calendar and moved the Alarm methods to live under the VAlarm struct. 
- Todo and Journal have setters for the properties listed in [RFC5545](https://www.rfc-editor.org/rfc/rfc5545) and [RFC7968](https://www.rfc-editor.org/rfc/rfc7968)
- Moved a bunch of the methods attached to `VEvent` to `ComponentBase` so that the Todo and Journal objects would also have access to them, without needing to duplicate the methods
- For a couple of the methods like `setPriority` and `setResources` I made them private on the ComponentBase and then added public methods on the Components they're valid in, Event and Todo. I'm not super married to this idea, there is probably a better way to handle this without duplicating too much code.
- I added new things to the bottom of the constant lists, and left all of the ComponentBase (previously Event) methods in the same order.
- The different components are ordered:
  - Struct
  - serialize methods (`serialize`, `Serialize`)
  - New method
  - Two Add methods (`AddEvent`, `AddVEvent`)
  - Getting all components method (`Events`)
  - Any property setters only for that component (`SetEndAt`)
  - Property setters that are shared between some (but not all) components (`SetPriority`)
  - Any existing getters (`GetEndAt`)

### CODE REVIEW

**Comment by spslater** [comment]
I've already notice a typo in [components.go](https://github.com/arran4/golang-ical/pull/66/files#diff-414491c8e37212605f612587cf5cb5dbf1711eef4b733970d280b57f4e1011ceR542) where the VTodo `setGeo` method should be `SetGeo` to make it public. I will hold off on pushing another commit in case any changes need to be made.

**Comment by spslater** [comment]
Workflow failed seems to be caused by an incident at Github, issue is resolved now, so we should be able to just rerun it.

https://www.githubstatus.com/incidents/0d1bcqt29hm2

**Comment by arran4** [comment]
Okay attempting to re-run them all

**Comment by arran4** [comment]
@spslater It still seems to be failing. However for much clearer reasons:
```
Run go test ./...
go: downloading github.com/stretchr/testify v1.7.0
go: downloading github.com/pmezard/go-difflib v1.0.0
go: downloading gopkg.in/yaml.v3 v3.0.0-20210107192922-49[6](https://github.com/arran4/golang-ical/actions/runs/4600085447/jobs/8187337848?pr=66#step:5:7)545a630[7](https://github.com/arran4/golang-ical/actions/runs/4600085447/jobs/8187337848?pr=66#step:5:8)b
go: downloading github.com/davecgh/go-spew v1.1.1
# github.com/arran4/golang-ical [github.com/arran4/golang-ical.test]
Error: ./components.go:6[9](https://github.com/arran4/golang-ical/actions/runs/4600085447/jobs/8187337848?pr=66#step:5:10)9:4: syntax error: unexpected newline, expecting comma or }
FAIL	github.com/arran4/golang-ical [build failed]
FAIL
Error: Process completed with exit code 2.
```

**Comment by spslater** [comment]
Whoops, not sure how I missed that, fixed it and a couple other things I caught.

**Comment by arran4** [comment]
@spslater There is a conflict.

**Comment by arran4** [comment]
@spslater I have attempted to resolve the conflict. Please take a look at some stage.

**Comment by arran4** [comment]
Bah I broke it.

**Comment by arran4** [comment]
Okay.. Github merge helped me mangle that.

**Comment by arran4** [comment]
Force pushed removal. Shouldn't have closed it though.

**Comment by spslater** [comment]
Looks like that force push overwrote some of the changes, I will see if I can get a clean merge with some small changes from my local copy.

**Comment by arran4** [comment]
Bah trashed more commits than I should have.

I had to restart the merge please look at https://github.com/arran4/golang-ical/pull/84

**Comment by arran4** [comment]
> Looks like that force push overwrote some of the changes, I will see if I can get a clean merge with some small changes from my local copy.

I think I salvaged it. Perhaps compare?

**Pull request closed without merging**
