### PR TITLE
Extended time parsing

### PR DESCRIPTION
**Pull request by shaohme**
Attempt to handle time parsing a little better.

### CODE REVIEW

**Comment by arran4** [comment]
@shaohme Is this one urgent, I am going have to leave it open a bit until I have more time to investigate it

**Comment by shaohme** [comment]
Not urgent.  I'm using my own branch in the meantime.
I just came across time parsing errors when dealing with my mixed .ics files from different sources and platforms.

**Review by JM-Lemmi — APPROVED** [review]
I didn't test everything, but the implementation is working as expected for me so far.

**Comment by arran4** [comment]
@JM-Lemmi (Thanks for picking this up) & @shaohme Hey, it  looks like I accepted another PR https://github.com/arran4/golang-ical/pull/47 before getting to this and it has caused a merge conflict. I was going to attempt to resolve it but it looks nontrivial. Perhaps another solution is necessary; I think the simplest possible change is to create new functions (names being illustrative not actual)
```
// Smart selection code here if still required
func (event *VEvent) getTimeProp(componentProperty ComponentProperty) (time.Time, error)
// The existing function def
func (event *VEvent) getTimePropFormatted(componentProperty ComponentProperty, formatted String) (time.Time, error)
// This PRs version
func (event *VEvent) getTimePropAllDay(componentProperty ComponentProperty, expectAllDay bool) (time.Time, error)
```
It doesn't look like a base version is really necessary as the repeated code is rather small.

We might have to rename the function @fty4 might be using (Sorry @fty4 please weigh in.)

**Comment by shaohme** [comment]
> @JM-Lemmi (Thanks for picking this up) & @shaohme Hey, it looks like I accepted another PR #47 before getting to this and it has caused a merge conflict. I was going to attempt to resolve it but it looks nontrivial. Perhaps another solution is necessary; I think the simplest possible change is to create new functions (names being illustrative not actual)
> 
> ```
> // Smart selection code here if still required
> func (event *VEvent) getTimeProp(componentProperty ComponentProperty) (time.Time, error)
> // The existing function def
> func (event *VEvent) getTimePropFormatted(componentProperty ComponentProperty, formatted String) (time.Time, error)
> // This PRs version
> func (event *VEvent) getTimePropAllDay(componentProperty ComponentProperty, expectAllDay bool) (time.Time, error)
> ```
> 
> It doesn't look like a base version is really necessary as the repeated code is rather small.
> 
> We might have to rename the function @fty4 might be using (Sorry @fty4 please weigh in.)

I just switched the format string with a boolean because the only users were GetAllDay* Get*At functions so it might as well reflect that :)

**Comment by shaohme** [comment]
@arran4 Was this not supported to be merged when #43 got closed?

**Comment by arran4** [comment]
You're right! So sorry.

**Pull request merged**
