### PR TITLE
Add ComponentPropertyRelatedTo; the VTODO component can have that

### PR DESCRIPTION
**Pull request by quite**

### CODE REVIEW

**Comment by quite** [comment]
@arran4 tiny addition here

**Review by arran4 — APPROVED** [review]
LGTM. 

https://icalendar.org/iCalendar-RFC-5545/3-8-4-5-related-to.html

**Comment by arran4** [comment]
What was the usecase?

**Comment by arran4** [comment]
https://github.com/arran4/golang-ical/releases/tag/v0.3.1

**Comment by quite** [comment]
> What was the usecase?

@arran4 i use [this task manager](https://github.com/tasks/tasks) and had created a task as a subtask of another task. Needed this to dig out the relation

**Comment by arran4** [comment]
I'm eventually going to add some better tests, and docs, etc, can you zip and upload an example ICS here -- or PR it in with a test.

**Comment by quite** [comment]
> I'm eventually going to add some better tests, and docs, etc, can you zip and upload an example ICS here -- or PR it in with a test. (Don't feel obliged please.)

I published my little cli tool here, perhaps something at least: https://codeberg.org/quite/qtodo

**Pull request merged**
